# Generated by Django 5.1.4 on 2025-01-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0002_alter_segment_options_segment_segment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='segment_number',
            field=models.IntegerField(),
        ),
    ]
