# Generated by Django 5.1.4 on 2025-08-18 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0009_subtitle_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspotifystate',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccessRefreshToken',
        ),
        migrations.DeleteModel(
            name='UserSpotifyState',
        ),
    ]
