# Generated by Django 5.1.4 on 2025-01-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ('subtitle', 'segment_number')},
        ),
        migrations.AddField(
            model_name='segment',
            name='segment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.CheckConstraint(condition=models.Q(('segment_number__gt', 0)), name='segment_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('subtitle', 'segment_number'), name='unique_segment_number_per_subtitle'),
        ),
    ]
