# Generated by Django 5.1.4 on 2025-01-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0005_alter_accessrefreshtoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpotifyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('state', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
