# Generated by Django 5.1.4 on 2025-07-30 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0007_like_alter_segment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActiveSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=255)),
                ('active_subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subtitles.subtitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_subtitles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'song_id')},
            },
        ),
    ]
