# Generated by Django 5.1.4 on 2025-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0008_useractivesubtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='title',
            field=models.CharField(default='dsdsd', max_length=255),
            preserve_default=False,
        ),
    ]
